USE [art_live]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[art_feriados](
	[fId] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [datetime2](0) NOT NULL,
	[description] [nvarchar](2000) NOT NULL
 CONSTRAINT [PK_art_feriados_fId] PRIMARY KEY CLUSTERED 
(
	[fId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
